# Runtime image for a web build generated on the host.
#
# Use this when Docker Desktop or WSL does not have enough memory to run the
# Next.js production build inside Docker:
#
#   pnpm -C web build
#   pnpm -C web build:vinext
#   docker build -f web/Dockerfile.prebuilt -t dify-mo-web:latest .

ARG DOCKER_PROXY=docker.m.daocloud.io
FROM ${DOCKER_PROXY}/library/node:22.22.1-alpine AS production
LABEL maintainer="takatost@gmail.com"

ARG ALPINE_MIRROR=https://mirrors.aliyun.com/alpine
ARG NPM_REGISTRY=https://registry.npmmirror.com

ENV npm_config_registry=${NPM_REGISTRY}
ENV pnpm_config_registry=${NPM_REGISTRY}
ENV COREPACK_NPM_REGISTRY=${NPM_REGISTRY}

RUN sed -i "s#https://dl-cdn.alpinelinux.org/alpine#${ALPINE_MIRROR}#g; s#http://dl-cdn.alpinelinux.org/alpine#${ALPINE_MIRROR}#g" /etc/apk/repositories
RUN apk add --no-cache tzdata
RUN npm config set registry ${NPM_REGISTRY}

ENV NODE_ENV=production
ENV EDITION=SELF_HOSTED
ENV DEPLOY_ENV=PRODUCTION
ENV CONSOLE_API_URL=http://127.0.0.1:5001
ENV APP_API_URL=http://127.0.0.1:5001
ENV MARKETPLACE_API_URL=https://marketplace.dify.ai
ENV MARKETPLACE_URL=https://marketplace.dify.ai
ENV PORT=3000
ENV EXPERIMENTAL_ENABLE_VINEXT=false
ENV NEXT_TELEMETRY_DISABLED=1

ENV TZ=UTC
RUN ln -s /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone

ARG dify_uid=1001
RUN addgroup -S -g ${dify_uid} dify && \
    adduser -S -u ${dify_uid} -G dify -s /bin/ash -h /home/dify dify && \
    mkdir /app && \
    chown -R dify:dify /app

WORKDIR /app

COPY --chown=dify:dify web/public ./targets/next/web/public
COPY --chown=dify:dify web/.next/standalone ./targets/next/
COPY --chown=dify:dify web/.next/static ./targets/next/web/.next/static
COPY --chown=dify:dify web/dist/standalone ./targets/vinext
COPY --chown=dify:dify --chmod=755 web/docker/entrypoint.sh ./entrypoint.sh

ARG COMMIT_SHA
ENV COMMIT_SHA=${COMMIT_SHA}

USER dify
EXPOSE 3000
ENTRYPOINT ["/bin/sh", "./entrypoint.sh"]
