**
!web/public/
!web/public/**
!web/.next/
!web/.next/standalone/
!web/.next/standalone/**
!web/.next/static/
!web/.next/static/**
!web/dist/
!web/dist/standalone/
!web/dist/standalone/**
!web/docker/
!web/docker/entrypoint.sh

.git
**/node_modules/.cache
**/.turbo
**/.pnpm-store
